name: prueba_tecnica
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  device_preview: ^1.2.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.3.0
  material_symbols_icons: ^4.2789.0

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icon/

  fonts:
    - family: YuGiOh
      fonts:
        - asset: assets/fonts/BelweBold.ttf
